package Ph;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.sql.*;
//import oracle.jdbc.OracleDriver;

public class Myframe extends javax.swing.JFrame 
{
    static File  My_File;
    private static Scanner Input;
    private static FileWriter Writer;
    private String S="";
    private ArrayList<Mmedicine> M=new ArrayList<Mmedicine>();
    private String []T;
    private static FileInputStream I;
    public Myframe() 
    {
      
        initComponents();
       
       
    }
  private static void CreateFile()
  {
      try 
      {
       My_File =new File("Information.txt");
         Writer=new FileWriter(My_File,true);
         Input=new Scanner(My_File);
        // I=new FileInputStream(My_File);
      }
      catch(FileNotFoundException Ex)
      {
          JOptionPane.showMessageDialog(null,"File Not Found","Error",JOptionPane.ERROR_MESSAGE);
      }
      catch(IOException Ex )
      {
           JOptionPane.showMessageDialog(null,"You can't write in this file","Error",JOptionPane.ERROR_MESSAGE);
      }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Exp Date");

        jLabel3.setText("Price");

        jLabel4.setText("ID");

        jLabel5.setText("Quantity");

        jLabel6.setText("Unit");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(33, 33, 33)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3)
                    .addComponent(jTextField6))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Save
        if(jTextField1.getText().isEmpty()|| jTextField2.getText().isEmpty() ||jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField6.getText().isEmpty() )
            JOptionPane.showMessageDialog(null, "Incomplete Information ","", JOptionPane.WARNING_MESSAGE);
        else 
        {
            try {
               CreateFile();
              if(!is_exsit(jTextField4.getText()))
              {
           Writer.append(jTextField1.getText()+',');
           Writer.append(jTextField2.getText()+',');
           Writer.append(jTextField3.getText()+',');
           Writer.append(jTextField4.getText()+',');
           Writer.append(jTextField5.getText()+',');
           Writer.append(jTextField6.getText()+"\n");
           
           JOptionPane.showMessageDialog(null, "You have successfully added the drug specification","", JOptionPane.INFORMATION_MESSAGE);
           jTextField1.setText("");
           jTextField2.setText("");
           jTextField3.setText("");
           jTextField4.setText("");
           jTextField5.setText("");
           jTextField6.setText("");
          // read_file();
           Writer.close();
              }
              
              else 
              {
                  JOptionPane.showMessageDialog(null, "This ID is Already exsit", "Error", JOptionPane.ERROR_MESSAGE);
                   jTextField1.setText("");
                   jTextField2.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   jTextField6.setText("");
              }
            }
            catch (IOException Ex)
            {
              JOptionPane.showMessageDialog(null,"You can't write in this file","Error",JOptionPane.ERROR_MESSAGE);
              return;
            }
            catch(NumberFormatException Ex)
            {
                JOptionPane.showMessageDialog(null,"please enter the Specifications in right way ","attention",JOptionPane.WARNING_MESSAGE);
                return;
            }
           
           
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Search
    CreateFile();
    String s="";
    boolean b=true;
    while(Input.hasNextLine())
    {
       S=Input.nextLine();
       T=S.split(",");
       if(!jTextField4.getText().isEmpty())
       {
          if(T[3].equals(jTextField4.getText()))
          {
              jTextField1.setText(T[0]);
              jTextField2.setText(T[1]);
              jTextField3.setText(T[2]);
            //  jTextField4.setText(T[3]);
              jTextField5.setText(T[4]);
              jTextField6.setText(T[5]);
          }
      
         
       }//if(!jTextField4.getText().isEmpty())
       
        else if(!jTextField1.getText().isEmpty())
       {
          if(T[0].equalsIgnoreCase(jTextField1.getText()))
          {
              jTextField2.setText(T[1]);
              jTextField3.setText(T[2]);
              jTextField4.setText(T[3]);
              jTextField5.setText(T[4]);
              jTextField6.setText(T[5]);
          }
      

         
       }//if(!jTextField1.getText().isEmpty())
       
          else if(!jTextField3.getText().isEmpty())
       {
          if(T[2].equals(jTextField3.getText()))
          {
              jTextField1.setText(T[0]);
              jTextField2.setText(T[1]);
              jTextField4.setText(T[3]);
              jTextField5.setText(T[4]);
              jTextField6.setText(T[5]);
          }
       

     
       }//if(!jTextField3.getText().isEmpty())
       
          else if(!jTextField5.getText().isEmpty())
       {
          if(T[4].equals(jTextField5.getText()))
          {
              jTextField1.setText(T[0]);
              jTextField2.setText(T[1]);
              jTextField3.setText(T[2]);
              jTextField4.setText(T[3]);
              jTextField6.setText(T[5]);
          }
       

     
       }//if(!jTextField5.getText().isEmpty())
       
          else if(!jTextField6.getText().isEmpty())
       {
          if(T[5].equals(jTextField6.getText()))
          {
              jTextField1.setText(T[0]);
              jTextField2.setText(T[1]);
              jTextField3.setText(T[2]);
              jTextField4.setText(T[3]);
              jTextField5.setText(T[4]);
          }
      

       }//if(!jTextField6.getText().isEmpty())
       
          else if(!jTextField2.getText().isEmpty())
          {
              JOptionPane.showMessageDialog(null, "you can't search by the date may be the result will not be  accurate", "Warning", JOptionPane.WARNING_MESSAGE);
              b=false;
              break;
          }
    }//while
    

  
  
     
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           //Update
        CreateFile();
        String New =new String("");
          
     if(jTextField4.getText().isEmpty())
      JOptionPane.showMessageDialog(null,"You should enter the ID to update the information ","Wrong",JOptionPane.WARNING_MESSAGE);
     
     else 
     {
         
     while(Input.hasNextLine())
     {
        
         S=Input.nextLine();
         
        
         T=S.split(",");
    
         if(jTextField4.getText().equals(T[3]))
         {
           if(!jTextField1.getText().isEmpty())
               New+=jTextField1.getText()+",";
           else
               New+=T[0]+",";
           
           if(!jTextField2.getText().isEmpty())
               New+=jTextField2.getText()+",";
           else
               New+=T[1]+",";
            
            
           if(!jTextField3.getText().isEmpty())
               New+=jTextField3.getText()+",";
           else
               New+=T[2]+",";
             
             
             New+=T[3]+",";
             
             
           if(!jTextField5.getText().isEmpty())
               New+=jTextField5.getText()+",";
           else
               New+=T[4]+",";
              
              
            if(!jTextField6.getText().isEmpty())
               New+=jTextField6.getText()+"\n";
           else
               New+=T[5]+"\n";
         }
         else
         {
              New+=S+"\n";
         }
        
      
 
            
         
     
     }
    try
       {
          FileWriter W=new FileWriter(My_File);
         W.write(New);
         W.close();
       }
    catch(IOException Ex)
       {
         JOptionPane.showMessageDialog(null,"You can't write in this file","Error",JOptionPane.ERROR_MESSAGE);
       }
       
     }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Delete
        CreateFile();
        String New =new String("");
        if(jTextField4.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"You should enter the ID to Delete the medicine ","Wrong",JOptionPane.WARNING_MESSAGE);
        else 
        {
            while(Input.hasNextLine())
            {
                S=Input.nextLine();
                T=S.split(",");
                if(jTextField4.getText().equals(T[3]))
                    continue;
                else
                    New +=S+"\n";
            }
            try 
            {
                FileWriter W=new FileWriter (My_File);
                W.write(New);
                W.close();
            }
            catch(IOException Ex)
            {
                JOptionPane.showMessageDialog(null,"You can't write in this file","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed


     
     public  void read_file ()
     { 
         Mmedicine x=new Mmedicine();
         try
         {
         Scanner Input =new Scanner(My_File);
         while (Input.hasNextLine())
         {
             
             S=Input.nextLine();
             T=S.split(",");
             x.set_Name(T[0]);
             x.set_Exp_Date(T[1]);
             x.set_price(T[2]);
             x.set_ID(T[3]);
             x.set_Quntity(T[4]);
             x.set_Unit(T[5]);
             M.add(x);
         }
         }
         catch(FileNotFoundException Ex)
         {
             JOptionPane.showMessageDialog(null,"The file not found", "Error",JOptionPane.ERROR_MESSAGE);
         }
     }
     private boolean is_exsit(String ID)
     {
         boolean b=false;
         read_file();
         for(int i=0;i<M.size();i++)
         
             if(ID.equals(M.get(i).get_ID()))
             {
                b=true ;
                break;
             }
        
         return b;
     }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws SQLException,ClassNotFoundException {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Myframe().setVisible(true);
         
            }
        });
       
     
             /* String query1 = "Select AL_Name from AirLine";

            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
  
        try (Connection conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe", "c##saif_khalid", "123456")) {

            if (conn != null) {
                PreparedStatement stmt = conn.prepareStatement(query1);

              ResultSet  rs = stmt.executeQuery();

                while (rs.next()) {
                   System.out.println(rs.getString("AL_Name"));

                }


            } else {
                System.out.println("Failed to make connection!");
            }

        } catch (SQLException se) {
            System.err.format("SQL State: %s\n%s", se.getSQLState(), se.getMessage());
        } catch (Exception se) {
            se.printStackTrace();
        } */
       
        
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
