/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mohamad_ui;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author pc
 */
public class manager_page extends javax.swing.JFrame {

    /**
     * Creates new form manager_page
     */
     boolean a = true;
    public manager_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header = new javax.swing.JPanel();
        minMaxCloseIcon = new javax.swing.JPanel();
        minButton = new javax.swing.JPanel();
        minIcon = new javax.swing.JLabel();
        maxButton = new javax.swing.JPanel();
        maxIcone = new javax.swing.JLabel();
        closeButton = new javax.swing.JPanel();
        closeIcon = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linemenu = new javax.swing.JPanel();
        menuback = new javax.swing.JPanel();
        IconMenu = new javax.swing.JLabel();
        menuHide = new javax.swing.JPanel();
        profileInfo = new javax.swing.JPanel();
        profile = new javax.swing.JPanel();
        profilePage = new javax.swing.JPanel();
        profilePic = new javax.swing.JLabel();
        managerName = new javax.swing.JLabel();
        massages = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        headerForMain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(0, 0, 51));
        header.setPreferredSize(new java.awt.Dimension(576, 50));
        header.setLayout(new java.awt.BorderLayout());

        minMaxCloseIcon.setBackground(new java.awt.Color(0, 0, 51));
        minMaxCloseIcon.setPreferredSize(new java.awt.Dimension(150, 50));
        minMaxCloseIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minButton.setBackground(new java.awt.Color(0, 0, 51));

        minIcon.setBackground(new java.awt.Color(0, 0, 51));
        minIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout minButtonLayout = new javax.swing.GroupLayout(minButton);
        minButton.setLayout(minButtonLayout);
        minButtonLayout.setHorizontalGroup(
            minButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minButtonLayout.createSequentialGroup()
                .addComponent(minIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        minButtonLayout.setVerticalGroup(
            minButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minButtonLayout.createSequentialGroup()
                .addComponent(minIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        minMaxCloseIcon.add(minButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        maxButton.setBackground(new java.awt.Color(0, 0, 51));

        maxIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/full_screen_32px.png"))); // NOI18N
        maxIcone.setPreferredSize(new java.awt.Dimension(50, 50));
        maxIcone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxIconeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxIconeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxIconeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout maxButtonLayout = new javax.swing.GroupLayout(maxButton);
        maxButton.setLayout(maxButtonLayout);
        maxButtonLayout.setHorizontalGroup(
            maxButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maxIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        maxButtonLayout.setVerticalGroup(
            maxButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maxIcone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        minMaxCloseIcon.add(maxButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        closeButton.setBackground(new java.awt.Color(0, 0, 51));

        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/close.png"))); // NOI18N
        closeIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeButtonLayout = new javax.swing.GroupLayout(closeButton);
        closeButton.setLayout(closeButtonLayout);
        closeButtonLayout.setHorizontalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        closeButtonLayout.setVerticalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        minMaxCloseIcon.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        header.add(minMaxCloseIcon, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(250, 501));
        menu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(0, 0, 51));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 493));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linemenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linemenuLayout = new javax.swing.GroupLayout(linemenu);
        linemenu.setLayout(linemenuLayout);
        linemenuLayout.setHorizontalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linemenuLayout.setVerticalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(linemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        menuback.setBackground(new java.awt.Color(0, 0, 51));
        menuback.setLayout(new java.awt.BorderLayout());

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/back_32px.png"))); // NOI18N
        IconMenu.setMaximumSize(new java.awt.Dimension(100, 100));
        IconMenu.setMinimumSize(new java.awt.Dimension(50, 50));
        IconMenu.setName(""); // NOI18N
        IconMenu.setPreferredSize(new java.awt.Dimension(50, 50));
        IconMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconMenuMouseExited(evt);
            }
        });
        menuback.add(IconMenu, java.awt.BorderLayout.CENTER);

        menuIcon.add(menuback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        menu.add(menuIcon, java.awt.BorderLayout.LINE_START);

        menuHide.setBackground(new java.awt.Color(25, 29, 74));
        menuHide.setLayout(new java.awt.BorderLayout());

        profileInfo.setBackground(new java.awt.Color(25, 29, 74));
        profileInfo.setPreferredSize(new java.awt.Dimension(200, 150));
        profileInfo.setLayout(new java.awt.BorderLayout());

        profile.setBackground(new java.awt.Color(25, 29, 74));

        profilePage.setBackground(new java.awt.Color(25, 29, 74));

        profilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/image 11.jpg"))); // NOI18N
        profilePic.setPreferredSize(new java.awt.Dimension(100, 100));
        profilePic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilePicMouseExited(evt);
            }
        });

        javax.swing.GroupLayout profilePageLayout = new javax.swing.GroupLayout(profilePage);
        profilePage.setLayout(profilePageLayout);
        profilePageLayout.setHorizontalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilePageLayout.setVerticalGroup(
            profilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(profilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        profileInfo.add(profile, java.awt.BorderLayout.PAGE_START);

        managerName.setForeground(new java.awt.Color(255, 255, 255));
        managerName.setText(" Manager name: mohamad isa");
        profileInfo.add(managerName, java.awt.BorderLayout.CENTER);

        menuHide.add(profileInfo, java.awt.BorderLayout.PAGE_END);

        massages.setBackground(new java.awt.Color(25, 29, 74));
        menuHide.add(massages, java.awt.BorderLayout.CENTER);

        menu.add(menuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        main.setBackground(new java.awt.Color(73, 128, 242));
        main.setLayout(new java.awt.BorderLayout());

        headerForMain.setBackground(new java.awt.Color(73, 128, 242));
        headerForMain.setPreferredSize(new java.awt.Dimension(485, 150));
        headerForMain.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(485, 50));
        jPanel3.setLayout(new java.awt.GridLayout());
        headerForMain.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        main.add(headerForMain, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu(JPanel h1, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(25, 29, 74));
            
        }
        else{
            h1.setBackground(new Color(5, 10, 46));
        }
    }
    
    public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel Button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(Button,"/design_imgs/menu_32px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
            changeimage(Button,"/design_imgs/back_32px.png");
        }
        
    }
    
    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseEntered
       changecolor(closeButton, new Color(25, 29, 74));
    }//GEN-LAST:event_closeIconMouseEntered

    private void closeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseExited
        changecolor(closeButton, new Color(5, 10, 46));
    }//GEN-LAST:event_closeIconMouseExited

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void maxIconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxIconeMouseClicked
        if(this.getExtendedState()!= manager_page.MAXIMIZED_BOTH){
          this.setExtendedState(manager_page.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(manager_page.NORMAL);
        }
        
    }//GEN-LAST:event_maxIconeMouseClicked

    private void maxIconeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxIconeMouseEntered
         changecolor(maxButton, new Color(25, 29, 74));
    }//GEN-LAST:event_maxIconeMouseEntered

    private void maxIconeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxIconeMouseExited
        changecolor(maxButton, new Color(5, 10, 46));
    }//GEN-LAST:event_maxIconeMouseExited

    private void IconMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMenuMouseClicked
         clickmenu(menuback,1);
       
        //create void for methode hide and show panel menu
        if(a==true){
          hideshow(menu, a ,IconMenu);
          SwingUtilities.updateComponentTreeUI(this);
         
          a=false;
        }
        else{
            hideshow(menu, a ,IconMenu);
            SwingUtilities.updateComponentTreeUI(this);
         
            a=true;
        }
        
    }//GEN-LAST:event_IconMenuMouseClicked

    private void IconMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMenuMouseEntered
        changecolor(linemenu, new Color(247, 78, 105));
    }//GEN-LAST:event_IconMenuMouseEntered

    private void IconMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMenuMouseExited
         changecolor(linemenu, new Color(5, 10, 46));
    }//GEN-LAST:event_IconMenuMouseExited

    private void profilePicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePicMouseEntered
        changecolor(profilePage, new Color(153,153,153));
    }//GEN-LAST:event_profilePicMouseEntered

    private void profilePicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePicMouseExited
        changecolor(profilePage, new Color(25,29,74));
    }//GEN-LAST:event_profilePicMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconMenu;
    private javax.swing.JPanel closeButton;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JPanel header;
    private javax.swing.JPanel headerForMain;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel linemenu;
    private javax.swing.JPanel main;
    private javax.swing.JLabel managerName;
    private javax.swing.JPanel massages;
    private javax.swing.JPanel maxButton;
    private javax.swing.JLabel maxIcone;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuHide;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel menuback;
    private javax.swing.JPanel minButton;
    private javax.swing.JLabel minIcon;
    private javax.swing.JPanel minMaxCloseIcon;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel profileInfo;
    private javax.swing.JPanel profilePage;
    private javax.swing.JLabel profilePic;
    // End of variables declaration//GEN-END:variables
}
