/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mohamad_ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicComboBoxEditor;


/**
 *
 * @author pc
 */
public class manager_page extends javax.swing.JFrame {

    /**
     * Creates new form manager_page
     */
    

     boolean a = true;
    public manager_page() {
        initComponents();
        myComponents();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    private void myComponents(){
    searchAbout.setBackground(Color.white);
    Border border = new LineBorder(Color.getHSBColor(88, 88, 88), 2, true);
     searchAbout.setBorder(border);
   
}
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        minMaxCloseIcon = new javax.swing.JPanel();
        minButton = new javax.swing.JPanel();
        minIcon = new javax.swing.JLabel();
        maxButton = new javax.swing.JPanel();
        maxIcone = new javax.swing.JLabel();
        closeButton = new javax.swing.JPanel();
        closeIcon = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linemenu = new javax.swing.JPanel();
        menuback = new javax.swing.JPanel();
        IconMenu = new javax.swing.JLabel();
        menuHide = new javax.swing.JPanel();
        prfileInfo = new javax.swing.JPanel();
        profilepiclayout = new javax.swing.JPanel();
        profilePicpanel = new javax.swing.JPanel();
        profilePicIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        masseges = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        headerForMain = new javax.swing.JPanel();
        searchPosition = new javax.swing.JPanel();
        searchLayout = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();
        submitSearch = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchAbout = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        offersPanel = new javax.swing.JPanel();
        offerGroup1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        offerGroup2 = new javax.swing.JPanel();
        offer4 = new javax.swing.JPanel();
        offer5 = new javax.swing.JPanel();
        offer6 = new javax.swing.JPanel();
        offerGroup3 = new javax.swing.JPanel();
        offer7 = new javax.swing.JPanel();
        offer8 = new javax.swing.JPanel();
        offer9 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(141, 221, 210));
        header.setPreferredSize(new java.awt.Dimension(576, 50));
        header.setLayout(new java.awt.BorderLayout());

        minMaxCloseIcon.setBackground(new java.awt.Color(141, 221, 210));
        minMaxCloseIcon.setPreferredSize(new java.awt.Dimension(150, 50));
        minMaxCloseIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minButton.setBackground(new java.awt.Color(141, 221, 210));

        minIcon.setBackground(new java.awt.Color(141, 221, 210));
        minIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout minButtonLayout = new javax.swing.GroupLayout(minButton);
        minButton.setLayout(minButtonLayout);
        minButtonLayout.setHorizontalGroup(
            minButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minButtonLayout.createSequentialGroup()
                .addComponent(minIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        minButtonLayout.setVerticalGroup(
            minButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minButtonLayout.createSequentialGroup()
                .addComponent(minIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        minMaxCloseIcon.add(minButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        maxButton.setBackground(new java.awt.Color(141, 221, 210));

        maxIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/full_screen_32px.png"))); // NOI18N
        maxIcone.setPreferredSize(new java.awt.Dimension(50, 50));
        maxIcone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxIconeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxIconeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxIconeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout maxButtonLayout = new javax.swing.GroupLayout(maxButton);
        maxButton.setLayout(maxButtonLayout);
        maxButtonLayout.setHorizontalGroup(
            maxButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maxButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maxIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );
        maxButtonLayout.setVerticalGroup(
            maxButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maxButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maxIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        minMaxCloseIcon.add(maxButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        closeButton.setBackground(new java.awt.Color(141, 221, 210));

        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/close.png"))); // NOI18N
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeButtonLayout = new javax.swing.GroupLayout(closeButton);
        closeButton.setLayout(closeButtonLayout);
        closeButtonLayout.setHorizontalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        closeButtonLayout.setVerticalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        minMaxCloseIcon.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        header.add(minMaxCloseIcon, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(250, 501));
        menu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(141, 221, 210));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 493));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linemenu.setBackground(new java.awt.Color(141, 221, 210));
        linemenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linemenuLayout = new javax.swing.GroupLayout(linemenu);
        linemenu.setLayout(linemenuLayout);
        linemenuLayout.setHorizontalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linemenuLayout.setVerticalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(linemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        menuback.setBackground(new java.awt.Color(141, 221, 210));
        menuback.setLayout(new java.awt.BorderLayout());

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/back_32px.png"))); // NOI18N
        IconMenu.setMaximumSize(new java.awt.Dimension(100, 100));
        IconMenu.setName(""); // NOI18N
        IconMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconMenuMouseExited(evt);
            }
        });
        menuback.add(IconMenu, java.awt.BorderLayout.CENTER);

        menuIcon.add(menuback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        menu.add(menuIcon, java.awt.BorderLayout.LINE_START);

        menuHide.setBackground(new java.awt.Color(204, 255, 255));
        menuHide.setLayout(new java.awt.BorderLayout());

        prfileInfo.setBackground(new java.awt.Color(255, 255, 255));
        prfileInfo.setPreferredSize(new java.awt.Dimension(200, 160));
        prfileInfo.setLayout(new java.awt.BorderLayout());

        profilepiclayout.setBackground(new java.awt.Color(141, 221, 210));
        profilepiclayout.setPreferredSize(new java.awt.Dimension(198, 130));
        profilepiclayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilePicpanel.setBackground(new java.awt.Color(141, 221, 210));
        profilePicpanel.setPreferredSize(new java.awt.Dimension(126, 126));

        profilePicIcon.setBackground(new java.awt.Color(141, 221, 210));
        profilePicIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/Capture5.PNG"))); // NOI18N
        profilePicIcon.setPreferredSize(new java.awt.Dimension(124, 124));
        profilePicIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePicIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilePicIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout profilePicpanelLayout = new javax.swing.GroupLayout(profilePicpanel);
        profilePicpanel.setLayout(profilePicpanelLayout);
        profilePicpanelLayout.setHorizontalGroup(
            profilePicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePicIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        profilePicpanelLayout.setVerticalGroup(
            profilePicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePicpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePicIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        profilepiclayout.add(profilePicpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        prfileInfo.add(profilepiclayout, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(141, 221, 210));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Update");
        jPanel1.add(jLabel1);

        prfileInfo.add(jPanel1, java.awt.BorderLayout.CENTER);

        menuHide.add(prfileInfo, java.awt.BorderLayout.PAGE_START);

        masseges.setBackground(new java.awt.Color(141, 221, 210));

        javax.swing.GroupLayout massegesLayout = new javax.swing.GroupLayout(masseges);
        masseges.setLayout(massegesLayout);
        massegesLayout.setHorizontalGroup(
            massegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        massegesLayout.setVerticalGroup(
            massegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        menuHide.add(masseges, java.awt.BorderLayout.CENTER);

        menu.add(menuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        main.setBackground(new java.awt.Color(51, 102, 255));
        main.setLayout(new java.awt.BorderLayout());

        headerForMain.setBackground(new java.awt.Color(51, 102, 255));
        headerForMain.setPreferredSize(new java.awt.Dimension(485, 150));
        headerForMain.setLayout(new java.awt.BorderLayout());

        searchPosition.setBackground(new java.awt.Color(255, 255, 255));
        searchPosition.setPreferredSize(new java.awt.Dimension(485, 50));

        searchLayout.setBackground(new java.awt.Color(255, 255, 255));
        searchLayout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        searchLayout.setPreferredSize(new java.awt.Dimension(402, 45));
        searchLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchText.setBorder(null);
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        searchLayout.add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 240, 40));

        submitSearch.setBackground(new java.awt.Color(204, 204, 204));
        submitSearch.setPreferredSize(new java.awt.Dimension(60, 60));
        submitSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitSearchMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_imgs/icons8-search-30.png"))); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout submitSearchLayout = new javax.swing.GroupLayout(submitSearch);
        submitSearch.setLayout(submitSearchLayout);
        submitSearchLayout.setHorizontalGroup(
            submitSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        submitSearchLayout.setVerticalGroup(
            submitSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitSearchLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        searchLayout.add(submitSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -20, 50, 70));

        searchAbout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "From", "To", "Travelling Way", "Price" }));
        searchAbout.setBorder(null);
        searchAbout.setPreferredSize(new java.awt.Dimension(10, 20));
        searchAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAboutActionPerformed(evt);
            }
        });
        searchLayout.add(searchAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -10, 110, 70));

        searchPosition.add(searchLayout);

        headerForMain.add(searchPosition, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(3, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(235, 65));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 88, 88));
        jLabel2.setText("Easy Travel");
        jLabel2.setPreferredSize(new java.awt.Dimension(225, 40));
        jPanel7.add(jLabel2);

        jPanel6.add(jPanel7);

        headerForMain.add(jPanel6, java.awt.BorderLayout.CENTER);

        main.add(headerForMain, java.awt.BorderLayout.PAGE_START);

        offersPanel.setBackground(new java.awt.Color(255, 255, 255));
        offersPanel.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        offerGroup1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 100));

        scroll.setBorder(null);

        description.setColumns(20);
        description.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        description.setForeground(new java.awt.Color(88, 88, 88));
        description.setRows(5);
        description.setText("For Easy and Affordable travel\nwith all the Transportation Available.");
        description.setBorder(null);
        description.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        description.setFocusable(false);
        description.setPreferredSize(new java.awt.Dimension(460, 155));
        scroll.setViewportView(description);

        jPanel4.add(scroll);

        offerGroup1.add(jPanel4);

        offersPanel.add(offerGroup1);

        offerGroup2.setBackground(new java.awt.Color(255, 255, 255));
        offerGroup2.setLayout(new java.awt.GridLayout(0, 3, 10, 0));

        offer4.setBackground(new java.awt.Color(255, 255, 255));
        offer4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout offer4Layout = new javax.swing.GroupLayout(offer4);
        offer4.setLayout(offer4Layout);
        offer4Layout.setHorizontalGroup(
            offer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        offer4Layout.setVerticalGroup(
            offer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        offerGroup2.add(offer4);

        offer5.setBackground(new java.awt.Color(255, 255, 255));
        offer5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout offer5Layout = new javax.swing.GroupLayout(offer5);
        offer5.setLayout(offer5Layout);
        offer5Layout.setHorizontalGroup(
            offer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        offer5Layout.setVerticalGroup(
            offer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        offerGroup2.add(offer5);

        offer6.setBackground(new java.awt.Color(255, 255, 255));
        offer6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout offer6Layout = new javax.swing.GroupLayout(offer6);
        offer6.setLayout(offer6Layout);
        offer6Layout.setHorizontalGroup(
            offer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        offer6Layout.setVerticalGroup(
            offer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        offerGroup2.add(offer6);

        offersPanel.add(offerGroup2);

        offerGroup3.setBackground(new java.awt.Color(255, 255, 255));
        offerGroup3.setLayout(new java.awt.GridLayout(0, 3, 10, 0));

        offer7.setBackground(new java.awt.Color(255, 255, 255));
        offer7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout offer7Layout = new javax.swing.GroupLayout(offer7);
        offer7.setLayout(offer7Layout);
        offer7Layout.setHorizontalGroup(
            offer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        offer7Layout.setVerticalGroup(
            offer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        offerGroup3.add(offer7);

        offer8.setBackground(new java.awt.Color(255, 255, 255));
        offer8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout offer8Layout = new javax.swing.GroupLayout(offer8);
        offer8.setLayout(offer8Layout);
        offer8Layout.setHorizontalGroup(
            offer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        offer8Layout.setVerticalGroup(
            offer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        offerGroup3.add(offer8);

        offer9.setBackground(new java.awt.Color(255, 255, 255));
        offer9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout offer9Layout = new javax.swing.GroupLayout(offer9);
        offer9.setLayout(offer9Layout);
        offer9Layout.setHorizontalGroup(
            offer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        offer9Layout.setVerticalGroup(
            offer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        offerGroup3.add(offer9);

        offersPanel.add(offerGroup3);

        main.add(offersPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu(JPanel h1, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(141,221,210));
            
        }
        else{
            h1.setBackground(new Color(141,221,210));
        }
    }
    
    public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel Button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(Button,"/design_imgs/menu_32px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
            changeimage(Button,"/design_imgs/back_32px.png");
        }
        
    }
    
    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseEntered
       changecolor(closeButton, new Color(153,153,153));
    }//GEN-LAST:event_closeIconMouseEntered

    private void closeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseExited
        changecolor(closeButton, new Color(141,221,210));
    }//GEN-LAST:event_closeIconMouseExited

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void maxIconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxIconeMouseClicked
        if(this.getExtendedState()!= manager_page.MAXIMIZED_BOTH){
          this.setExtendedState(manager_page.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(manager_page.NORMAL);
        }
        scroll.setBorder(null);
    }//GEN-LAST:event_maxIconeMouseClicked

    private void maxIconeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxIconeMouseEntered
         changecolor(maxButton, new Color(153,153,153));
    }//GEN-LAST:event_maxIconeMouseEntered

    private void maxIconeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxIconeMouseExited
        changecolor(maxButton, new Color(141,221,210));
    }//GEN-LAST:event_maxIconeMouseExited

    private void IconMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMenuMouseClicked
         clickmenu(menuback,1);
       
        //create void for methode hide and show panel menu
        if(a==true){
          hideshow(menu, a ,IconMenu);
          SwingUtilities.updateComponentTreeUI(this);
         
          a=false;
        }
        else{
            hideshow(menu, a ,IconMenu);
            SwingUtilities.updateComponentTreeUI(this);
         
            a=true;
        }
        searchText.setBorder(null);
        scroll.setBorder(null);
    }//GEN-LAST:event_IconMenuMouseClicked

    private void IconMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMenuMouseEntered
        changecolor(linemenu, new Color(153,153,153));
        
    }//GEN-LAST:event_IconMenuMouseEntered

    private void IconMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMenuMouseExited
         changecolor(linemenu, new Color(141,221,210));
    }//GEN-LAST:event_IconMenuMouseExited

    private void submitSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitSearchMouseEntered
        changecolor(submitSearch, new Color(204,204,255));
    }//GEN-LAST:event_submitSearchMouseEntered

    private void submitSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitSearchMouseExited
        changecolor(submitSearch, new Color(204,204,204));
    }//GEN-LAST:event_submitSearchMouseExited

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void profilePicIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePicIconMouseEntered
       
    }//GEN-LAST:event_profilePicIconMouseEntered

    private void profilePicIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePicIconMouseExited
        
    }//GEN-LAST:event_profilePicIconMouseExited

    private void searchAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_page().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconMenu;
    private javax.swing.JPanel closeButton;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JTextArea description;
    private javax.swing.JPanel header;
    private javax.swing.JPanel headerForMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel linemenu;
    private javax.swing.JPanel main;
    private javax.swing.JPanel masseges;
    private javax.swing.JPanel maxButton;
    private javax.swing.JLabel maxIcone;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuHide;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel menuback;
    private javax.swing.JPanel minButton;
    private javax.swing.JLabel minIcon;
    private javax.swing.JPanel minMaxCloseIcon;
    private javax.swing.JPanel offer4;
    private javax.swing.JPanel offer5;
    private javax.swing.JPanel offer6;
    private javax.swing.JPanel offer7;
    private javax.swing.JPanel offer8;
    private javax.swing.JPanel offer9;
    private javax.swing.JPanel offerGroup1;
    private javax.swing.JPanel offerGroup2;
    private javax.swing.JPanel offerGroup3;
    private javax.swing.JPanel offersPanel;
    private javax.swing.JPanel prfileInfo;
    private javax.swing.JLabel profilePicIcon;
    private javax.swing.JPanel profilePicpanel;
    private javax.swing.JPanel profilepiclayout;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JComboBox<String> searchAbout;
    private javax.swing.JPanel searchLayout;
    private javax.swing.JPanel searchPosition;
    private javax.swing.JTextField searchText;
    private javax.swing.JPanel submitSearch;
    // End of variables declaration//GEN-END:variables

    
}
